apiVersion: v1
kind: Service
metadata:
  name: stress-node-port
spec:
  type: NodePort
  ports:
    - ports: 8022
      targetPort: 22
      nodePort: 31515
  selector:
    component: linux
